### ISSUE TITLE
Ansible Plug-in Malfunction

### ISSUE THREAD

**Issue by tarundalai1999** [jenkinsci/ansible-plugin#172]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
 TASK [Gathering Facts] *********************************************************
fatal: [App01-Staging]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ubuntu@172.31.47.102: Permission denied (publickey).", "unreachable": true}

PLAY RECAP *********************************************************************
App01-Staging              : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   

FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:308)
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:256)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:164)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:526)
	at hudson.model.Run.execute(Run.java:1895)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
ERROR: Ansible playbook execution failed
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

When i execute the playbook on jenkins, via ansible plugin, it giving an error.
![Screenshot (1)](https://github.com/jenkinsci/ansible-plugin/assets/109707593/45cdfecd-5e57-4cc0-a51c-40870db670ff)

### Reproduction steps

Install and Unistall Ansible Plugin, and created an instance several times

### Expected Results

Playbook should execute

### Actual Results

it will fetch the file and give a sucess

### Are you interested in contributing a fix?

Yes

**Comment by tarundalai1999** [comment]
also my security groups of AWS is all correct and other playbooks are running. but this having an problem.
